# Generated by Django 5.1.4 on 2024-12-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, choices=[('XSM', 'XSM'), ('SM', 'SM'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=255, null=True)),
                ('price', models.IntegerField()),
                ('group', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('CHILDREN', 'CHILDREN')], max_length=255, null=True)),
            ],
        ),
    ]
